### PR TITLE
Fetch additonal owner info when fetching repos

### PR DESCRIPTION
**Pull request by hehao98**

### CODE REVIEW

**Review by frank-zsy — COMMENTED** [review]
LGTM

**Comment by frank-zsy** [comment]
Sorry, I looked into the code, actually if you want to fetch additional owner info of orgs, you may not retrieve data from nodes(repos), you can retrieve data from organization level to avoid fetch redundant data(num times of org data). @hehao98

**Comment by frank-zsy** [comment]
Unless you also want to retrieve more organization info when you only need to fetch data of one certain repo.

**Comment by hehao98** [comment]
I agree it is much better to write new API for retrieving user information...If there is any need we can add new API for retrieving full organization or user info(I have not found it on existing code...)

I did this on repo because it is simpler to implement and it won't have any additional API resource cost(I avoided fetching edges). Also, I think it is useful if one can know whether a repository belongs to an organization or user account, etc.

**Comment by frank-zsy** [comment]
Yes, this is my problem, actually this project is not a common library to fetch GitHub data as the API design is based on my needs in real work. Maybe I should re-design the API and implement a more common version. @hehao98

**Pull request merged**
